### ISSUE TITLE
Handle quests with multiple rewards

### ISSUE THREAD

**Issue by HeleleF** [HeleleF/mymap#3]
#### Description
Quests can have multiple rewards, but the current way of handling quests shows only one icon, because only one reward is expected. It would be nice to have something like a question mark as an icon, that shows all available rewards when clicked.

#### Files
- `app/map/map.component.ts`
- `app/popup/popup.component.html`

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [ ] Create / find / choose a fitting image icon for multiple rewards
- [ ] Update icon-image property in `addLayer()` to use this icon when needed
- [ ] Implement logic to detect and handle multiple rewards in the popup

**Comment by HeleleF** [comment]
Right now the main focus is gyms, so everything quest-related is gone for now...
May get revisited later 🤔
